### ISSUE TITLE
build issue

### ISSUE THREAD

**Issue by FrTime** [wlburks/journal#1]
In Dockerfile, change ruby version:

```
from ruby:3.1.2
```

In docker-compose.yml, point it at local Dockerfile:

```
services:
  journal:
    build:
      context: .
```
